import json
import os
import re
import subprocess
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
PACKAGE_FILE = BASE_DIR / "oimodeler" / "__init__.py"


def get_push_range():
    """
    Return (before, after) for a GitHub push event.

    Returns (None, None) when the workflow was not triggered by a push.
    """

    event_path = os.environ.get("GITHUB_EVENT_PATH")

    if not event_path:
        return None, None

    try:
        with open(event_path, "r") as f:
            event = json.load(f)
    except (OSError, json.JSONDecodeError):
        return None, None

    before = event.get("before")
    after = event.get("after")

    if not before or not after:
        return None, None

    # GitHub uses an all-zero SHA for the first push of a branch.
    if before == "0" * 40:
        return None, after

    return before, after


def get_commits():
    """
    Get commits introduced by the current push.

    For a push event:
        before..after

    For workflow_dispatch or another event:
        commits since the latest tag.
    """

    before, after = get_push_range()

    if before and after:
        print(f"Push range: {before}..{after}")

        result = subprocess.check_output(
            [
                "git",
                "log",
                "--format=%s",
                f"{before}..{after}",
            ],
            text=True,
        )

        return result.splitlines()

    print("No push range available.")

    # Fallback for workflow_dispatch / local execution
    try:
        last_tag = subprocess.check_output(
            ["git", "describe", "--tags", "--abbrev=0"],
            text=True,
        ).strip()

        print(f"Using commits since tag: {last_tag}")

        result = subprocess.check_output(
            [
                "git",
                "log",
                "--format=%s",
                f"{last_tag}..HEAD",
            ],
            text=True,
        )

        return result.splitlines()

    except subprocess.CalledProcessError:
        print("No tag found. Using all commits.")

        result = subprocess.check_output(
            ["git", "log", "--format=%s"],
            text=True,
        )

        return result.splitlines()


def detect_level(commits):
    """
    Detect the highest requested version bump.

    Priority:
        MAJOR > MINOR > PATCH
    """

    level = None

    for i, message in enumerate(commits):
        message = message.strip()

        print(f"{i + 1}: {message}")

        # Ignore commits generated by this workflow.
        if message.startswith("BUMP:"):
            continue

        if message.startswith("MAJOR:"):
            level = "MAJOR"

        elif message.startswith("MINOR:") and level != "MAJOR":
            level = "MINOR"

        elif message.startswith("PATCH:") and level not in ("MAJOR", "MINOR"):
            level = "PATCH"

    return level


def bump(version, level):
    major, minor, patch = map(int, version.split("."))

    if level == "MAJOR":
        return f"{major + 1}.0.0"

    if level == "MINOR":
        return f"{major}.{minor + 1}.0"

    if level == "PATCH":
        return f"{major}.{minor}.{patch + 1}"

    return None


def set_github_output(name, value):
    """
    Set an output for GitHub Actions.
    """

    github_output = os.environ.get("GITHUB_OUTPUT")

    if github_output:
        with open(github_output, "a") as f:
            f.write(f"{name}={value}\n")


def update_version(current, new_version):
    content = PACKAGE_FILE.read_text()

    updated = re.sub(
        r'(__version__\s*=\s*)"[^"]+"',
        rf'\1"{new_version}"',
        content,
    )

    PACKAGE_FILE.write_text(updated)


def main():
    content = PACKAGE_FILE.read_text()

    match = re.search(
        r'__version__\s*=\s*"([^"]+)"',
        content,
    )

    if not match:
        raise ValueError("__version__ not found")

    current = match.group(1)

    print(f"Current version: {current}")

    commits = get_commits()

    if not commits:
        print("No commits found.")
        set_github_output("bump", "false")
        return

    level = detect_level(commits)

    if level is None:
        print("No version bump requested.")
        set_github_output("bump", "false")
        return

    new_version = bump(current, level)

    print(f"Version bump: {current} -> {new_version} ({level})")

    update_version(current, new_version)

    set_github_output("bump", "true")


if __name__ == "__main__":
    main()