[amp]
name = "amplitude"
value = 1
description = "Amplitude"
mini = 0
maxi = 1

[A_V]
name = "A_V"
description = "Extinction in V band"
unit = "mag"
free = false
mini = 0
maxi = 50

[cosi]
name = "cosi"
description = "The cosine of the inclination"
mini = 0
maxi = 1

[d]
name = "d"
description = "Diameter"
unit = "mas"
mini = 0

[default]
name = ""
value = 0
mini = "-inf"
maxi = "inf"
description = ""
unit = "one"
free = true
error = 0

[din]
name = "din"
description = "Inner Diameter"
unit = "mas"
mini = 0

[dim]
name = "dim"
value = 128
description = "Dimension in pixels"
free = false
mini = 1

[dist]
name = "dist"
description = "Distance"
unit = "pc"
free = false

[dout]
name = "dout"
description = "Outer Diameter"
unit = "mas"
mini = 0

[elong]
name = "elong"
value = 1
description = "Elongation Ratio"
mini = 1

[f]
name = "f"
value = 1
description = "flux"
mini = 0
maxi = 1
free = true

[fwhm]
name = "fwhm"
description = "FWHM"
unit = "mas"
mini = 0

[fov]
name = "fov"
description = "The interferometric field of view"
unit = "mas"
free = false

[hlr]
name = "hlr"
description = "Half-light/-flux radius"
unit = "mas"
mini = 0

[index]
name = "index"
value = 1
description = "Index"

[mjd]
name = "mjd"
description = "MJD"
unit = "day"

[p]
name = "pow"
description = "Power exponent"
mini = -1
maxi = 0

[pa]
name = "pa"
description = "Major-axis Position angle"
unit = "deg"
mini = -180
maxi = 180

[pixSize]
name = "pixSize"
description = "Pixel Size"
unit = "mas"
free = false
mini = 0

[r]
name = "r"
description = "Radius"
unit = "mas"

[rin]
name = "rin"
description = "Inner radius"
unit = "au"
mini = 0

[rout]
name = "rout"
description = "Outer radius"
unit = "au"
mini = 0

[skw]
name = "skw"
description = "Skewedness"
mini = 0
maxi = 1

[scale]
name = "scale"
value = 1
description = "Scaling Factor"

[skwPa]
name = "skwPa"
description = "Skewedness Position angle"
unit = "deg"
mini = -180
maxi = 180

[w]
name = "w"
description = "Width"
unit = "mas"
mini = 0
maxi = 1

[wl]
name = "wl"
description = "Wavelength"
unit = "m"
mini = 0

[x]
name = "x"
description = "x position"
unit = "mas"
free = false

[y]
name = "y"
description = "y position"
unit = "mas"
free = false
