name: Auto Bump Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'oimodeler/**'

  bump-version:
    needs: check-changes
    if: needs.check-changes.outputs.code == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Bump version
        run: python bump_version.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bump-version
          title: "Auto bump version"
          commit-message: "Auto bump version"
          delete-branch: true