name: Build Docs (RTD API)

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect docs changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'README.md'

      - name: Trigger Read the Docs build
        if: steps.changes.outputs.docs == 'true'
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
            https://readthedocs.org/api/v3/projects/oimodeler/versions/latest/builds/

      - name: Skip build
        if: steps.changes.outputs.docs != 'true'
        run: echo "No docs changes → skipping RTD build"