name: Auto bump patch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-version:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Bump version
        run: python bump_version.py

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "Auto bump patch version"

          git pull --rebase origin main || true
          git push origin HEAD:main